# Generated by Django 5.2.8 on 2025-12-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cover_image',
            field=models.ImageField(blank=True, default='cover_images/default.jpg', upload_to='cover_images'),
        ),
    ]
