# Generated by Django 5.2.8 on 2025-11-18 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_asset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='event_asset/default_img.jpg', null=True, upload_to='event_asset'),
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
