# Generated by Django 5.2.8 on 2025-11-19 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_user_alter_event_asset_delete_participant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ManyToManyField(related_name='event_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
