# Generated by Django 5.2.8 on 2026-03-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_about_event_registered_event_tags_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='avatar',
            field=models.ImageField(default='event_asset/default_img.jpg', upload_to='avatars'),
        ),
    ]
